a = input('digite algo')
print('a classe é',type(a))
print('tem apenas espacos?', a.isspace())
print('é um numero?', a.isnumeric())
print('é alfabético?', a.isalpha())
print('é alfanumérico?', a.isalnum())
print('está em maiusculas?', a.isupper())
print('está em minusculas?', a.islower())
print('está capitalizada?', a.istitle())